<?php

declare(strict_types=1);

namespace Studio\Gesso\Fuzz;

use const JSON_PRESERVE_ZERO_FRACTION;
use const JSON_THROW_ON_ERROR;

use JsonException;
use LogicException;
use PHPUnit\Framework\Assert;

use function array_is_list;
use function array_key_exists;
use function is_array;
use function json_decode;
use function json_encode;
use function sprintf;
use function str_replace;
use function var_export;

/**
 * One branch-complete response payload generated by
 * {@see OpenApiResponseExplorer} for an SDK deserializer round trip.
 */
final readonly class GeneratedResponseCase
{
    /**
     * @param array<string, mixed> $schema Converted JSON Schema used for generation and round-trip validation.
     */
    public function __construct(
        public mixed $body,
        public int $status,
        public string $contentType,
        public int $seed,
        public int $caseIndex,
        public ?string $pinnedBranch,
        private string $specName,
        private string $method,
        private string $matchedPath,
        private array $schema,
        private int $extraCases = 0,
    ) {}

    /**
     * Return the generated body in the decoded JSON shape expected by SDK
     * deserializers: objects become stdClass instances, arrays stay arrays,
     * and scalar response schemas stay scalar.
     *
     * @throws JsonException
     */
    public function bodyAsObject(): mixed
    {
        return json_decode(json_encode($this->body, JSON_THROW_ON_ERROR), flags: JSON_THROW_ON_ERROR);
    }

    /**
     * Convert a generated JSON object or array for array-typed consumers.
     *
     * @return null|array<array-key, mixed>
     *
     * @throws JsonException
     * @throws LogicException when the generated response body is a scalar
     */
    public function bodyAsArray(): ?array
    {
        if ($this->body === null) {
            return null;
        }

        $body = json_decode(json_encode($this->body, JSON_THROW_ON_ERROR), true, flags: JSON_THROW_ON_ERROR);
        if (!is_array($body)) {
            throw new LogicException(
                'GeneratedResponseCase::bodyAsArray() requires a JSON object or array body; use body directly for a scalar response.',
            );
        }

        return $body;
    }

    /**
     * Assert that an SDK's re-encoded value is still schema-valid and has
     * preserved every generated key/value. JSON lists compare exactly;
     * objects may contain additional SDK-produced keys.
     */
    public function assertRoundTrip(mixed $reEncoded): void
    {
        try {
            $actual = self::normaliseForComparison($reEncoded);
        } catch (JsonException $e) {
            Assert::fail(sprintf(
                'SDK round trip result cannot be encoded as JSON: %s. %s',
                $e->getMessage(),
                $this->failureContext(),
            ));
        }

        if (!SchemaValueValidator::isValid($reEncoded, $this->schema)) {
            Assert::fail(
                'SDK round trip does not satisfy the resolved response schema. ' . $this->failureContext(),
            );
        }

        $generated = self::normaliseForComparison($this->body);
        $mismatch = self::fidelityMismatch($generated, $actual, '');
        if ($mismatch !== null) {
            Assert::fail('SDK round trip lost generated response fidelity: ' . $mismatch . '. ' . $this->failureContext());
        }
    }

    public function replaySnippet(): string
    {
        $extraCases = $this->extraCases > 0 ? sprintf(', extraCases: %d', $this->extraCases) : '';

        return sprintf(
            'OpenApiResponseExplorer::explore(%s, %s, %s, %d, %s, seed: %d%s)->cases[%d]',
            var_export($this->specName, true),
            var_export($this->method, true),
            var_export($this->matchedPath, true),
            $this->status,
            var_export($this->contentType, true),
            $this->seed,
            $extraCases,
            $this->caseIndex,
        );
    }

    private static function normaliseForComparison(mixed $value): mixed
    {
        return json_decode(
            json_encode($value, JSON_THROW_ON_ERROR | JSON_PRESERVE_ZERO_FRACTION),
            true,
            flags: JSON_THROW_ON_ERROR,
        );
    }

    private static function fidelityMismatch(mixed $generated, mixed $actual, string $pointer): ?string
    {
        if (!is_array($generated)) {
            return $generated === $actual
                ? null
                : sprintf("value at '%s' changed", self::displayPointer($pointer));
        }

        if (array_is_list($generated)) {
            return is_array($actual) && array_is_list($actual) && $generated === $actual
                ? null
                : sprintf("list at '%s' changed", self::displayPointer($pointer));
        }

        if (!is_array($actual) || array_is_list($actual)) {
            return sprintf("object at '%s' changed", self::displayPointer($pointer));
        }

        foreach ($generated as $key => $value) {
            $childPointer = $pointer . '/' . self::escapePointerToken((string) $key);
            if (!array_key_exists($key, $actual)) {
                return sprintf(
                    "missing generated key '%s' at '%s'",
                    $key,
                    self::displayPointer($pointer),
                );
            }

            $mismatch = self::fidelityMismatch($value, $actual[$key], $childPointer);
            if ($mismatch !== null) {
                return $mismatch;
            }
        }

        return null;
    }

    private static function displayPointer(string $pointer): string
    {
        return $pointer === '' ? '/' : $pointer;
    }

    private static function escapePointerToken(string $token): string
    {
        return str_replace(['~', '/'], ['~0', '~1'], $token);
    }

    private function failureContext(): string
    {
        return sprintf(
            'seed=%d, case=%d, pinned=%s; replay: %s',
            $this->seed,
            $this->caseIndex,
            $this->pinnedBranch ?? 'none',
            $this->replaySnippet(),
        );
    }
}
